# Generated by Django 5.2.6 on 2025-09-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image2',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image3',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
