# Generated by Django 5.2.6 on 2025-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_category_item_item_image_item_item_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='on_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
